// <auto-generated />
using System;
using HelloDotNetCoreWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloDotNetCoreWebAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20241111091625_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HelloDotNetCoreWebAPI.Data.HangHoaEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("discount")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("loaiId")
                        .HasColumnType("int");

                    b.Property<int>("loai_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("loai_id");

                    b.ToTable("hang_hoa", (string)null);
                });

            modelBuilder.Entity("HelloDotNetCoreWebAPI.Data.LoaiEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("loai");
                });

            modelBuilder.Entity("HelloDotNetCoreWebAPI.Data.NguoiDungEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("HelloDotNetCoreWebAPI.Data.HangHoaEntity", b =>
                {
                    b.HasOne("HelloDotNetCoreWebAPI.Data.LoaiEntity", "loai")
                        .WithMany("listHangHoa")
                        .HasForeignKey("loai_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loai");
                });

            modelBuilder.Entity("HelloDotNetCoreWebAPI.Data.LoaiEntity", b =>
                {
                    b.Navigation("listHangHoa");
                });
#pragma warning restore 612, 618
        }
    }
}
